# Generated by Django 5.2 on 2025-04-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('web_url', models.CharField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
    ]
