# Generated by Django 5.2 on 2025-04-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('idnp', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('address', models.CharField()),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(unique=True)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
