# Generated by Django 5.2 on 2025-04-15 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('stack', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('dot_net', '.NET'), ('react', 'React'), ('go_lang', 'Go Lang'), ('cpp', 'C++'), ('next_js', 'Next Js'), ('node_js', 'Node Js'), ('js_ts', 'Javascript/Typescript')], default='python')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'db_table': 'internships',
            },
        ),
    ]
