# Generated by Django 5.2 on 2025-04-15 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('app', 'Approved'), ('rej', 'Rejected'), ('prg', 'In progress')], default='prg', max_length=3)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships.internship')),
                ('student', models.ForeignKey(db_column='student_idnp', on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'db_table': 'applications',
                'constraints': [models.UniqueConstraint(fields=('student', 'internship'), name='unique_student_internship')],
            },
        ),
    ]
